version: '2'
services:
    web:
        build: .
        ports:
            - "${PORT:-5002}:${PORT:-5002}"
        environment:
          - DATABASE_URL=${DATABASE_URL:-postgresql+psycopg2://e2e:e2e@db/e2e2}
          - PORT=${PORT:-5002}
        volumes:
            - ./app:/app
            - ./migrations:/migrations
        depends_on:
          - db

    db:
      image: postgres:12.1-alpine
      environment:
        - TZ=UTC
        - POSTGRES_USER=e2e
        - POSTGRES_PASSWORD=e2e
        - POSTGRES_DB=e2e
      ports:
        - "5001:5432"
      volumes:
        - ./backup_data:/var/lib/postgresql/data