version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - ./app:/app
#            - ./migrations:/migrations
        depends_on:
          - db

    db:
      image: postgres:12.1-alpine
      environment:
        - TZ=UTC
        - POSTGRES_USER=e2e
        - POSTGRES_PASSWORD=e2e
        - POSTGRES_DB=e2e
      ports:
        - "5001:5432"
