"""empty message

Revision ID: 04a18afbc96c
Revises: 6cb8792ac0d6
Create Date: 2022-08-31 03:32:11.679404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a18afbc96c'
down_revision = '6cb8792ac0d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metrics_pipeline', 'duration_build')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics_pipeline', sa.Column('duration_build', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
