"""empty message

Revision ID: 5684fb25dcfd
Revises: 04a18afbc96c
Create Date: 2022-12-26 11:39:14.758024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5684fb25dcfd'
down_revision = '04a18afbc96c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics_job', sa.Column('duration_up_without_pull', sa.Integer(), nullable=True))
    op.add_column('metrics_job', sa.Column('duration_pull', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metrics_job', 'duration_pull')
    op.drop_column('metrics_job', 'duration_up_without_pull')
    # ### end Alembic commands ###
